version: '3.9'

services:
  seq:
    image: datalust/seq:latest
    container_name: hello-world-seq
    ports:
      - 5341:80
    environment:
      - ACCEPT_EULA=Y

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: hello-world-db-server
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=S3cr3t!!
  
  api:
    container_name: hello-world-api
    build:
      context: .
      dockerfile: "src\\HelloWorld.Api\\Dockerfile"
    ports:
      - 5000:80
      - 5001:443
    environment:
      - "ConnectionStrings__HelloWorldDatabase=Server=db;Database=HelloWorldDB;User=SA;Password=S3cr3t!!" 
      - "Serilog__WriteTo__0__Args__serverUrl=http://seq:5341" 
    depends_on:
      - seq
      - db

